use crate::ast::{Program, Expression};

grammar;

pub Prog: Program = {
    "def" "main" "(" <parameter: Var> ")" ":" <body: Expr> => Program { parameter , body },
}

Expr: Expression = {
    <x:Var> => Expression::Variable(x),
    <n: Num> => Expression::Number(n),
    "let" <x: Var> "=" <e1: Expr> "in" <e2: Expr> => Expression::Let(x, Box::new(e1), Box::new(e2)),
    "add1" "(" <e: Expr> ")" => Expression::Add1(Box::new(e)),
    "sub1" "(" <e: Expr> ")" => Expression::Sub1(Box::new(e)),
}

Var: String = <s:r"[a-zA-Z][a-zA-Z0-9_]*"> => String::from(s);

Num: i64 = {
  <s:r"[+-]?[0-9]+"> => s.parse().unwrap()
}
