use std::str::FromStr;
use crate::syntax::{Exp};

grammar;

// First the lexemes (not strictly necessary in LALRPOP)
NUM: i64 = <s:r"[+-]?[0-9]+"> => i64::from_str(s).unwrap();
ID: String = <s:r"[a-zA-Z][a-zA-Z0-9_]*"> => String::from(s);
PRINT: () = "print";
LET: () = "let";
IN: () = "in";
LPAREN: () = "(";
RPAREN: () = ")";
EQ: () = "=";
COMMA: () = ",";
MAYCOMMA: () = ",?";
PLUS: () = "+";

pub Exp: Exp = {
    LET <mut bindings: Bindings> IN <body: Exp> => { bindings.reverse(); Exp::Let { bindings, body: Box::new(body) } },
    SumExp,
}

// Using left recursion this time
pub SumExp: Exp = {
    <e1: SumExp> PLUS <e2: AddendExp> => Exp::Add(Box::new(e1), Box::new(e2)),
    AddendExp,
}

pub AddendExp: Exp = {
    <n: NUM> => Exp::Num(n),
    <id: ID> => Exp::Var(id),
    PRINT LPAREN <e: Exp> RPAREN => Exp::Print(Box::new(e)),
    LPAREN <e: Exp> RPAREN => e,
}

Bindings: Vec<(String, Exp)> = {
    <b: ID> EQ <e: Exp> => vec![(b, e)],
    <mut bs:Bindings> COMMA <b: ID> EQ <e: Exp> => {
        bs.push((b, e));
        bs
    }
}
